proj/config/routes.rb
Rails.application.routes.draw do
  root 'links#index'



  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, skip: [:sessions]
  	as :user do
  		get 'login' => 'devise/sessions#new', as: :new_user_session
  		post 'login' => 'devise/sessions#create', as: :user_session
  		delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  	end
    #devise_for :users,

  resources :comments, only: [:create, :destroy]

  resources :users, only: [:show] do
    resources :links, except: [:index, :show]
  end

  resources :links, only: [:index, :show] do
    resources :comments, only: [:index]
    member do
      put "like",    to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
  end


get '*path' => redirect('/') # Catches bad routes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

proj/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proj/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
  validates_presence_of :body, :user_id

  def commenter
  	self.user.username
  end
end

proj/app/models/link.rb
class Link < ApplicationRecord
	validates_presence_of :title, :url
	belongs_to :user
	has_many :comments
	has_many :linktags
	has_many :tags, through: :linktags
	acts_as_votable

	def all_tags=(names)
		self.tags = names.split(",").map do |name|
			Tag.where(name: name.strip).first_or_create!
		end
	end

	def all_tags
		self.tags.map{|t| t.name}.join(" ")
	end

	def owner
		self.user.username
	end

	def self.search(term)
		links = Tag.find_by_name(term).try(:links)
  		if links.nil? || links.empty?
    		self.order('id DESC')
    	else
    		links
  		end
	end
end

proj/app/models/linktag.rb
class Linktag < ApplicationRecord
  belongs_to :link
  belongs_to :tag
end

proj/app/models/tag.rb
class Tag < ApplicationRecord
	has_many :linktags
	has_many :links, through: :linktags

end

proj/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :links
  has_many :comments

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.username = auth.info.name   # assuming the user model has a name
    # user.image = auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
   end
  end

end

proj/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, :except => [:show, :index]


  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

proj/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@comments = Comment.where(link_id: params[:link_id])
 		render json: @comments.to_json(methods: :commenter)
	end

	def create
			@comment = Comment.new(comment_params)
			@comment.user_id = current_user.id
		respond_to do |format|
			if @comment.save
				format.html
				format.json{ render json: @comment.to_json(methods: :commenter) }
			else
				redirect_to link_path(@comment.link), alert: @comment.errors.full_messages.to_sentence
			end
		end
	end


	def destroy
		comment = Comment.find(params[:id])
		if comment.user == current_user || comment.link.user == current_user
			comment.destroy
		  redirect_to comment.link
		else
		  redirect_to comment.link, alert: "You are not authorized to delete this comment"
		end
	end


	private

		def comment_params
			params.require(:comment).permit(:body, :link_id, :id)
		end
end

proj/app/controllers/links_controller.rb
class LinksController < ApplicationController
	before_action :set_link, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

	def index
		@links = Link.search(params[:term])
	end

	def show
		#store id collection on show page
		@ids = Link.ids
		 current_user ? @cid = current_user.id : @cid = 0
		respond_to do |format|
		 if @link
			 format.html
			 format.json {render json: @link}
		 end
	 end
	end

	def new
		@link = current_user.links.build
	end

	def create

		@link = current_user.links.build(link_params)
		if @link.valid?
			@link.save
			redirect_to links_path, notice: "Success!"
		else
			flash.now[:alert]= @link.errors.full_messages.to_sentence
			render :new
		end
	end

	def edit
	end

	def update
		if current_user == @link.user
			@link.update(link_params)
			redirect_to links_path, notice: "Updated"
		else
			redirect_to links_path, alert: "You are not authorized to edit this link"
		end
	end

	def destroy
		@link.destroy if @link.user == current_user
		redirect_to links_path, notice: "Deleted"
	end

	def upvote
		@link.upvote_by current_user
  		redirect_to :back
	end

	def downvote
		@link.downvote_by current_user
  		redirect_to :back
	end

	private

		def link_params
			params.require(:link).permit(:user_id, :title, :url, :all_tags, :term)
		end

		def set_link
			@link = Link.find(params[:id])
		  rescue ActiveRecord::RecordNotFound
			redirect_to root_url, alert: "Record not found."
		end
end

proj/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
    
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

proj/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@links = Link.where(user: @user).order('id DESC')
	end
end

proj/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def main
	end
	
end

proj/app/helpers/application_helper.rb
module ApplicationHelper
end

proj/app/helpers/comments_helper.rb
module CommentsHelper
end

proj/app/helpers/links_helper.rb
module LinksHelper
end

proj/app/helpers/user_helper.rb
module UserHelper
end

proj/app/helpers/welcome_helper.rb
module WelcomeHelper
end

proj/app/views/comments/_comment.html.erb
<div class="comment">
	<p class="lead"><%= comment.body%>
		<small>Submitted by
			<%= link_to comment.commenter, user_path(comment.user) %>
			<% if comment.user == current_user %>
			<%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Are you sure?" } %>
			<% end %>
		</small>
	</p>
</div>

proj/app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");

var size = parseInt($('#comment-size').html());
size ++;
$('#comment-size').html(size);

$('#new_comment input[type=submit]').attr('disabled', false);

$('#comment_body').val('')

proj/app/views/layouts/_flash.html.erb
<% if flash.any? %>
<% if !flash.notice.blank? %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if !flash.alert.blank? %>
<p class="alert alert-danger"><%= alert %></p>
<% end %>
<% end %>

proj/app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">

    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- This toggles link elements into a dropdown button -->

    <div class="navbar-brand"><%= link_to "Flinks", root_path %></div>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="nav navbar-nav pull-xs-right">
            <% if user_signed_in? %>

            <%= link_to "Submit Link", new_user_link_path(current_user), class:"nav-item nav-link" %>
            <%= link_to current_user.username, user_path(current_user), class:"nav-item nav-link"%>
            <%= link_to "Edit account", edit_user_registration_path(@user), class:"nav-item nav-link" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-item nav-link" %>

        <% else %>
            <%= link_to "Log In", new_user_session_path, class:"nav-item nav-link" %>

            <% end %>
        </div>
    </div>

    <div class="fave-btn">
      <%= link_to "Show Faves", class:"nav-item nav-link" %>
    </div>
    <div class="form-inline ">

        <%= form_tag(links_path, method: :get, class:"input-group" ) do %>
        <%= text_field_tag :term, params[:term], placeholder: "Search by tag...", class:"form-control" %>
        <button class="btn btn-secondary" type="submit">Search</button>
        <% end %>

    </div>

</nav>

proj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Proj</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all'%>
        <%= javascript_include_tag 'application' %>
    </head>

    <body>

        <header>
            <%= render 'layouts/header' %>
        </header>

        <%= render 'layouts/flash' %>

        <div id="main_content" class="container">
            <div id="content" class="col-md-9 center-block">
                <%= yield %>
            </div>

        </div>

        <script type="text/javascript">
        $('.link').each(function(index){
           var id = $(this).find('div.btn').attr('btn-id')
        	if (localStorage['favourite' + id] == 'fave') {
        		$(this).addClass('fave');
        	}
        });
        // Add this to on button click
        $('.fave-btn').click(function(event){
          event.preventDefault();
          $('.link').filter(':not(.fave)').toggle();
        })

        </script>
    </body>
</html>

proj/app/views/links/_link.html.erb
<%= form_for ([current_user, link]) do |f| %>
<div class="form_group">
	<%= f.label :title %>
	<%= f.text_field :title, class:"form-control"%>
</div>

<div class="form_group">
	<%= f.label :url %>
	<%= f.text_field :url, class:"form-control" %>
</div>

<div class="form_group">
	<%= f.label "Tags" %>
	<%= f.text_field :all_tags, placeholder: "Insert tags eg: trial, ruby...", class:"form-control" %>
</div>
<%= f.submit class: "btn btn-secondary"%>

<% end %>

proj/app/views/links/_linktags.html.erb
<% link.tags.map do |t| %>
<%= link_to t.name, links_path(term: t.name) %>
<% end.join(", ") %>

proj/app/views/links/_listlink.html.erb
<h2>
	<%= link_to link.title, link_path(link), class: "link_title"%><br>
	<small>Submitted by
		<%= link_to link.owner, user_path(link.user) %></small>
	<br>

	<%= link_to "Visit URL", link.url, target: "_blank", class: "btn btn-secondary btn-sm"%>
	<%= link_to like_link_path(link), class: "btn btn-secondary btn-sm", method: :put do %>
	Upvote
	<%= link.get_upvotes.size %>
	<% end %>
	<%= link_to dislike_link_path(link), class: "btn btn-secondary btn-sm", method: :put do %>
	Downvote
	<%= link.get_downvotes.size %>
	<% end %>
	<div class="btn btn-secondary btn-sm", btn-id=<%= link.id %> > &hearts;</div>
</h2>

proj/app/views/links/edit.html.erb
<%= render @link %>

proj/app/views/links/index.html.erb
<% @links.each do |link| %>
<div class="link row clearfix">
	<%= render 'listlink', link: link %>
</div>
<% end %>

proj/app/views/links/new.html.erb
<h1>New Link</h1>
<%= render @link %>

proj/app/views/links/show.html.erb
<div class="next btn btn-secondary btn-sm" onclick="nxtLink()">Next Link</div>
<div class="link">
	<div class="link_title">
		<h2><%= @link.title%>
			<h2></div>

			<%= link_to "Visit URL", @link.url, target: "_blank", class: "btn btn-secondary btn-sm"%>
			<% if @link.user == current_user %>
			<%= link_to 'Edit', edit_user_link_path(@link), class: "btn btn-secondary btn-sm" %>
			<%= link_to 'Delete',user_link_path(@link), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-secondary btn-sm" %>
			<% end %><br>

			tags:
			<%= render "linktags", link: @link %>
			<br>

			<span id="comment-size"><%=  @link.comments.size %></span>
			<span id="comments-toggle">Comments</span>
			<br>
			<div id="comments">
			</div>

			<%= form_for @link.comments.build do |f| %>
			<%= f.hidden_field :link_id %>
			<%= f.text_area :body %>
			<br>
			<input type="submit" value="Add Comment", class: "btn btn-secondary new_comment"%>
			<% end %>
		</div>

		<%= content_tag :div, class: "linkIDs", data: {ids: @ids} do %>
		<% end %>
		<%= content_tag :div, class: "currentID", data: {cid: @cid} do %>
		<% end %>

		<script type="text/javascript">
			var current_user_id = parseInt($('.currentID').data('cid'));
			var all_ids = $('.linkIDs').data('ids');
			appendComment()
		</script>

proj/app/views/users/show.html.erb
<h2><%= @user.try(:username) %></h2>


<% @links.each do |link| %>
<div class="link row clearfix">
	<%= render 'links/listlink', link: link %>
</div>
<% end %>

proj/app/views/welcome/main.html.erb
<h1>Welcome</h1>